In [1]:
# Retail / E-Commerce Performance Analysis
# This file contains exploratory analysis used to investigate
# sales trends, category performance, and discount impact on profitability.

In [12]:
print("Setup working")

Setup working

In [13]:
import pandas as pd

In [14]:
orders = pd.read_csv("../data/Orders-Table 1.csv")

In [15]:
orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/16,6/16/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/15,10/18/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/15,10/18/15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [16]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [17]:
orders.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [18]:
orders.groupby("Category")["Sales"].sum()

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [19]:
orders.groupby("Category")[["Sales", "Profit"]].sum()

                       Sales       Profit
Category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

In [20]:
orders["Profit Margin"] = orders["Profit"] / orders["Sales"]

In [21]:
orders.groupby("Category")["Profit Margin"].mean()

Category
Furniture          0.038784
Office Supplies    0.138030
Technology         0.156138
Name: Profit Margin, dtype: float64

In [22]:
orders.groupby("Customer ID")["Sales"].sum()

Customer ID
AA-10315    5563.560
AA-10375    1056.390
AA-10480    1790.512
AA-10645    5086.935
AB-10015     886.156
              ...
XP-21865    2374.658
YC-21895    5454.350
YS-21880    6720.444
ZC-21910    8025.707
ZD-21925    1493.944
Name: Sales, Length: 793, dtype: float64

In [23]:
orders.groupby("Customer ID")["Sales"].sum().sort_values(ascending=False)

Customer ID
SM-20320    25043.050
TC-20980    19052.218
RB-19360    15117.339
TA-21385    14595.620
AB-10105    14473.571
              ...
RS-19870       22.328
MG-18205       16.739
CJ-11875       16.520
LD-16855        5.304
TS-21085        4.833
Name: Sales, Length: 793, dtype: float64

In [24]:
orders.groupby("Customer ID")["Profit"].sum().sort_values(ascending=False)

Customer ID
TC-20980    8981.3239
RB-19360    6976.0959
SC-20095    5757.4119
HL-15040    5622.4292
AB-10105    5444.8055
              ...
HG-14965   -2797.9635
SR-20425   -3333.9144
LF-17185   -3583.9770
GT-14635   -4108.6589
CS-12505   -6626.3895
Name: Profit, Length: 793, dtype: float64

In [25]:
top_customers = orders.groupby("Customer ID")["Profit"].sum().sort_values(ascending=False).head(5)
top_customers

Customer ID
TC-20980    8981.3239
RB-19360    6976.0959
SC-20095    5757.4119
HL-15040    5622.4292
AB-10105    5444.8055
Name: Profit, dtype: float64

In [26]:
top_customer_orders = orders[orders["Customer ID"].isin(top_customers.index)]
top_customer_orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Margin
447,448,CA-2016-166674,4/1/16,4/3/16,Second Class,RB-19360,Raymond Buch,Consumer,United States,Auburn,...,East,OFF-AR-10000588,Office Supplies,Art,Newell 345,59.52,3,0.0,15.4752,0.26
448,449,CA-2016-166674,4/1/16,4/3/16,Second Class,RB-19360,Raymond Buch,Consumer,United States,Auburn,...,East,OFF-ST-10001469,Office Supplies,Storage,Fellowes Bankers Box Recycled Super Stor/Drawer,161.94,3,0.0,9.7164,0.06
449,450,CA-2016-166674,4/1/16,4/3/16,Second Class,RB-19360,Raymond Buch,Consumer,United States,Auburn,...,East,OFF-AR-10001953,Office Supplies,Art,Boston 1645 Deluxe Heavier-Duty Electric Penci...,263.88,6,0.0,71.2476,0.27
450,451,CA-2016-166674,4/1/16,4/3/16,Second Class,RB-19360,Raymond Buch,Consumer,United States,Auburn,...,East,OFF-AR-10003156,Office Supplies,Art,50 Colored Long Pencils,30.48,3,0.0,7.9248,0.26
451,452,CA-2016-166674,4/1/16,4/3/16,Second Class,RB-19360,Raymond Buch,Consumer,United States,Auburn,...,East,OFF-AR-10004974,Office Supplies,Art,Newell 342,9.84,3,0.0,2.8536,0.29

In [27]:
top_customer_orders.groupby("Category")["Sales"].sum()

Category
Furniture           4527.981
Office Supplies    25492.303
Technology         45638.476
Name: Sales, dtype: float64

In [28]:
orders["Order Date"] = pd.to_datetime(orders["Order Date"])

/var/folders/mz/ckw32v610618vf31j8v951p00000gn/T/ipykernel_3265/1542484729.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders["Order Date"] = pd.to_datetime(orders["Order Date"])

In [29]:
orders["YearMonth"] = orders["Order Date"].dt.to_period("M")

In [30]:
orders.groupby("YearMonth")[["Sales", "Profit"]].sum()

                 Sales      Profit
YearMonth
2014-01     14236.8950   2450.1907
2014-02      4519.8920    862.3084
2014-03     55691.0090    498.7299
2014-04     28295.3450   3488.8352
2014-05     23648.2870   2738.7096
2014-06     34595.1276   4976.5244
2014-07     33946.3930   -841.4826
2014-08     27909.4685   5318.1050
2014-09     81777.3508   8328.0994
2014-10     31453.3930   3448.2573
2014-11     78628.7167   9292.1269
2014-12     69545.6205   8983.5699
2015-01     18174.0756  -3281.0070
2015-02     11951.4110   2813.8508
2015-03     38726.2520   9732.0978
2015-04     34195.2085   4187.4962
2015-05     30131.6865   4667.8690
2015-06     24797.2920   3335.5572
2015-07     28765.3250   3288.6483
2015-08     36898.3322   5355.8084
2015-09     64595.9180   8209.1627
2015-10     31404.9235   2817.3660
2015-11     75972.5635  12474.7884
2015-12     74919.5212   8016.9659
2016-01     18542.4910   2824.8233
2016-02     22978.8150   5004.5795
2016-03     51715.8750   3611.9680
2016-04     38750.0390   2977.8149
2016-05     56987.7280   8662.1464
2016-06     40344.5340   4750.3781
2016-07     39261.9630   4432.8779
2016-08     31115.3743   2062.0693
2016-09     73410.0249   9328.6576
2016-10     59687.7450  16243.1425
2016-11     79411.9658   4011.4075
2016-12     96999.0430  17885.3093
2017-01     43971.3740   7140.4391
2017-02     20301.1334   1613.8720
2017-03     58872.3528  14751.8915
2017-04     36521.5361    933.2900
2017-05     44261.1102   6342.5828
2017-06     52981.7257   8223.3357
2017-07     45264.4160   6952.6212
2017-08     63120.8880   9040.9557
2017-09     87866.6520  10991.5556
2017-10     77776.9232   9275.2755
2017-11    118447.8250   9690.1037
2017-12     83829.3188   8483.3468

In [31]:
monthly_data = orders.groupby("YearMonth")[["Sales", "Profit"]].sum()

monthly_data["Profit Margin"] = monthly_data["Profit"] / monthly_data["Sales"]

monthly_data

                 Sales      Profit  Profit Margin
YearMonth
2014-01     14236.8950   2450.1907       0.172101
2014-02      4519.8920    862.3084       0.190781
2014-03     55691.0090    498.7299       0.008955
2014-04     28295.3450   3488.8352       0.123301
2014-05     23648.2870   2738.7096       0.115810
2014-06     34595.1276   4976.5244       0.143850
2014-07     33946.3930   -841.4826      -0.024789
2014-08     27909.4685   5318.1050       0.190548
2014-09     81777.3508   8328.0994       0.101839
2014-10     31453.3930   3448.2573       0.109631
2014-11     78628.7167   9292.1269       0.118177
2014-12     69545.6205   8983.5699       0.129175
2015-01     18174.0756  -3281.0070      -0.180532
2015-02     11951.4110   2813.8508       0.235441
2015-03     38726.2520   9732.0978       0.251305
2015-04     34195.2085   4187.4962       0.122459
2015-05     30131.6865   4667.8690       0.154916
2015-06     24797.2920   3335.5572       0.134513
2015-07     28765.3250   3288.6483       0.114327
2015-08     36898.3322   5355.8084       0.145150
2015-09     64595.9180   8209.1627       0.127085
2015-10     31404.9235   2817.3660       0.089711
2015-11     75972.5635  12474.7884       0.164201
2015-12     74919.5212   8016.9659       0.107008
2016-01     18542.4910   2824.8233       0.152343
2016-02     22978.8150   5004.5795       0.217791
2016-03     51715.8750   3611.9680       0.069843
2016-04     38750.0390   2977.8149       0.076847
2016-05     56987.7280   8662.1464       0.152000
2016-06     40344.5340   4750.3781       0.117745
2016-07     39261.9630   4432.8779       0.112905
2016-08     31115.3743   2062.0693       0.066272
2016-09     73410.0249   9328.6576       0.127076
2016-10     59687.7450  16243.1425       0.272135
2016-11     79411.9658   4011.4075       0.050514
2016-12     96999.0430  17885.3093       0.184386
2017-01     43971.3740   7140.4391       0.162388
2017-02     20301.1334   1613.8720       0.079497
2017-03     58872.3528  14751.8915       0.250574
2017-04     36521.5361    933.2900       0.025555
2017-05     44261.1102   6342.5828       0.143299
2017-06     52981.7257   8223.3357       0.155211
2017-07     45264.4160   6952.6212       0.153600
2017-08     63120.8880   9040.9557       0.143232
2017-09     87866.6520  10991.5556       0.125094
2017-10     77776.9232   9275.2755       0.119255
2017-11    118447.8250   9690.1037       0.081809
2017-12     83829.3188   8483.3468       0.101198

In [32]:
orders.groupby("Discount")[["Sales", "Profit"]].mean()

               Sales      Profit
Discount
0.00      226.742074   66.900292
0.10      578.397351   96.055074
0.15      529.971567   27.288298
0.20      209.076940   24.702572
0.30      454.742974  -45.679636
0.32      536.794770  -88.560656
0.40      565.134874 -111.927429
0.45      498.634000 -226.646464
0.50      892.705152 -310.703456
0.60       48.150000  -43.077212
0.70       97.177708  -95.874060
0.80       56.545853 -101.796797

In [33]:
discount_analysis = orders.groupby("Discount")[["Sales", "Profit"]].mean()

discount_analysis["Profit Margin"] = discount_analysis["Profit"] / discount_analysis["Sales"]

discount_analysis

               Sales      Profit  Profit Margin
Discount
0.00      226.742074   66.900292       0.295050
0.10      578.397351   96.055074       0.166071
0.15      529.971567   27.288298       0.051490
0.20      209.076940   24.702572       0.118151
0.30      454.742974  -45.679636      -0.100452
0.32      536.794770  -88.560656      -0.164980
0.40      565.134874 -111.927429      -0.198054
0.45      498.634000 -226.646464      -0.454535
0.50      892.705152 -310.703456      -0.348047
0.60       48.150000  -43.077212      -0.894646
0.70       97.177708  -95.874060      -0.986585
0.80       56.545853 -101.796797      -1.800252

In [34]:
category_discount_analysis = (
    orders.groupby(["Category", "Discount"])[["Sales", "Profit"]]
    .mean()
    .reset_index()
)

category_discount_analysis["Profit Margin"] = (
    category_discount_analysis["Profit"] / category_discount_analysis["Sales"]
)

category_discount_analysis

           Category  Discount        Sales      Profit  Profit Margin
0         Furniture      0.00   306.250323   69.537173       0.227060
1         Furniture      0.10   613.608513   93.565946       0.152485
2         Furniture      0.15   529.971567   27.288298       0.051490
3         Furniture      0.20   352.245554   10.188535       0.028925
4         Furniture      0.30   448.064640  -48.177103      -0.107523
5         Furniture      0.32   536.794770  -88.560656      -0.164980
6         Furniture      0.40   608.192080 -215.831957      -0.354875
7         Furniture      0.45   498.634000 -226.646464      -0.454535
8         Furniture      0.50   388.582778 -238.355537      -0.613397
9         Furniture      0.60    48.150000  -43.077212      -0.894646
10        Furniture      0.70   163.958800 -259.662627      -1.583707
11  Office Supplies      0.00   141.307127   41.708567       0.295163
12  Office Supplies      0.10   270.259313   67.880050       0.251166
13  Office Supplies      0.20   105.883569   17.282486       0.163222
14  Office Supplies      0.70    59.366818  -43.687101      -0.735884
15  Office Supplies      0.80    56.545853 -101.796797      -1.800252
16       Technology      0.00   467.866987  158.881657       0.339587
17       Technology      0.10  1705.477500  416.042150       0.243945
18       Technology      0.20   374.451386   54.735560       0.146175
19       Technology      0.30   751.261000   65.207900       0.086798
20       Technology      0.40   540.483802  -52.440104      -0.097024
21       Technology      0.50  3161.255833 -636.269092      -0.201271
22       Technology      0.70   678.326478 -851.274743      -1.254963

In [35]:
orders.groupby(["Category", "Discount"])["Order ID"].count().reset_index()

           Category  Discount  Order ID
0         Furniture      0.00       836
1         Furniture      0.10        76
2         Furniture      0.15        52
3         Furniture      0.20       615
4         Furniture      0.30       222
5         Furniture      0.32        27
6         Furniture      0.40        75
7         Furniture      0.45        11
8         Furniture      0.50        54
9         Furniture      0.60       138
10        Furniture      0.70        15
11  Office Supplies      0.00      3129
12  Office Supplies      0.10        16
13  Office Supplies      0.20      2201
14  Office Supplies      0.70       380
15  Office Supplies      0.80       300
16       Technology      0.00       833
17       Technology      0.10         2
18       Technology      0.20       841
19       Technology      0.30         5
20       Technology      0.40       131
21       Technology      0.50        12
22       Technology      0.70        23

In [36]:
pd.pivot_table(
    orders,
    values="Order ID",
    index="Discount",
    columns="Category",
    aggfunc="count",
    fill_value=0
)

Category  Furniture  Office Supplies  Technology
Discount
0.00            836             3129         833
0.10             76               16           2
0.15             52                0           0
0.20            615             2201         841
0.30            222                0           5
0.32             27                0           0
0.40             75                0         131
0.45             11                0           0
0.50             54                0          12
0.60            138                0           0
0.70             15              380          23
0.80              0              300           0

In [37]:
# Step 1: remove 0% discount rows
filtered_orders = orders[orders["Discount"] > 0]

# Step 2: create pivot table
pivot = pd.pivot_table(
    filtered_orders,
    values="Order ID",
    index="Discount",
    columns="Category",
    aggfunc="count",
    fill_value=0
)

# Step 3: add totals column
pivot["Total"] = pivot.sum(axis=1)

# Step 4: add totals row
pivot.loc["Total"] = pivot.sum()

pivot

Category  Furniture  Office Supplies  Technology  Total
Discount
0.1              76               16           2     94
0.15             52                0           0     52
0.2             615             2201         841   3657
0.3             222                0           5    227
0.32             27                0           0     27
0.4              75                0         131    206
0.45             11                0           0     11
0.5              54                0          12     66
0.6             138                0           0    138
0.7              15              380          23    418
0.8               0              300           0    300
Total          1285             2897        1014   5196